import json,shutil,html,re,httpx
from pathlib import Path
R=Path(__file__).resolve().parents[1];A=R/'art/characters/explorer_b_face_balance_v4/assembly';OLD=R/'art/characters/explorer_b_young_bob_face_cleanup_v3/assembly';V=R/'artifacts/production-lab-20261003/review/character-face-balance-v4';V.mkdir(parents=True,exist_ok=True)
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def save(p,d):p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
check=read(A/'verification.json');assert check['status']=='passed';assert all(c['exposed_tooth_faces']==0 for c in check['tooth_visibility_rays'].values())
state={'date':'2026-10-05','state':'Blender_face_balance_crown_lowered_v4','blend':(A/'explorer_b_balanced_face_v4.blend').relative_to(R).as_posix(),'glb':(A/'explorer_b_balanced_face_v4.glb').relative_to(R).as_posix(),'face_source':'art/characters/explorer_b_face_multiview_meshhair_v2/head/model.fbx','hair_source':'art/characters/explorer_b_young_bob_face_cleanup_v3/hair/model.glb','hair_cards':False,'head_regenerated':False,'hair_regenerated':False,'new_total_credits':0,'remaining_credits':check['remaining_credits'],'total_scope_credits':check['total_spent'],'mouth_pose':'relaxed closed smile','original_open_pose_preserved':True,'mouth_control':'FACE_CONTROLS["mouth_open"]','eyes':'Separate globe objects with forward-facing brown irises, small catchlights, controlled reflections','lashes':'Contour-traced dark pigment, original skin atlas preserved','chin':'Front center gently raised/rounded','mouth_corners':'Slightly lowered, posterior lower molars tucked behind closed lip contour','teeth_exposure_test':'0 exposed tooth face centers in 6 sampled views','crown':'Upper height reduced by 0.0344 scene units; fringe and bob ends retained','full_face_rig':False,'game_low_poly_final':False,'review_url':'http://127.0.0.1:8842/character-face-balance-v4/'}
save(A/'workflow-status.json',state)
p=R/'docs/CHARACTER_GENERATION_POLICY.json';policy=read(p);policy.update(current_stage=state['state'],current_hybrid_output='art/characters/explorer_b_face_balance_v4',current_review_face_pose='relaxed_closed_smile',default_face_pose='relaxed_closed_smile');policy['latest_local_refinement_v4']={'date':'2026-10-05','user_instruction':'눈동자 쏠림, 턱 중앙 돌출, 죽어보이는 눈, 살구색 속눈썹, 높은 입꼬리와 보이는 치아를 보정. 헤어 정수리를 참고 이미지처럼 조금 납작하게.','state':state,'no_new_generation':True,'credits':0};save(p,policy)
p=R/'art/characters/explorer_b_pipeline_v3/pipeline.json';pipeline=read(p);pipeline.setdefault('historical_young_bob_cleanup_v3',pipeline.get('current_hybrid_bust',{}));pipeline.update(status=state['state'],current_hybrid_bust=state,current_integrated_face=state);pipeline['current_head_p2'].update(blend=state['blend'],state=state['state'],mouth_rest_prepared=True,eyes_separate=True,rigged=False);pipeline['user_direction']['latest_local_refinement']='Lower crown, forward gaze, lively eyes, dark lashes, softened chin and relaxed closed smile with hidden teeth';save(p,pipeline)
for n in ['front','angle','side','back','eyes_detail','mouth_front','mouth_closed','mouth_open','glb_roundtrip_front']:shutil.copy2(A/(n+'.png'),V/(n+'.png'))
for n in ['front','eyes_clean','mouth_closed']:shutil.copy2(OLD/(n+'.png'),V/('before_'+n+'.png'))
shutil.copy2(R/'art/references/explorer_b_integrated_face_haircards_v1/00_user_identity_reference.png',V/'identity.png');shutil.copy2(A/'explorer_b_balanced_face_v4.blend',V/'model.blend');shutil.copy2(A/'explorer_b_balanced_face_v4.glb',V/'model.glb')
for n in ['verification.json','workflow-status.json']:shutil.copy2(A/n,V/n)
fig=lambda n,t:f'<figure><a href="{n}.png" target="_blank"><img src="{n}.png" loading="lazy" alt="{html.escape(t)}"></a><figcaption>{html.escape(t)}</figcaption></figure>'
page='''<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>낮춘 정수리 · 자연스러운 눈과 미소</title><style>body{font:17px/1.7 system-ui;background:#161c25;color:#edf3fc;max-width:1250px;margin:32px auto;padding:0 24px}h1{font-size:32px}h2{margin-top:36px}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:20px}figure{margin:0}img{width:100%;border-radius:12px}figcaption{padding:9px;color:#c7d2e1}.note{background:#27374a;padding:18px;border-radius:12px;margin:20px 0}a{color:#a8d2ff}button{padding:10px 18px;margin-right:10px;font:inherit;border-radius:8px;background:#355775;color:white;border:0;cursor:pointer}table{width:100%;border-collapse:collapse}td{padding:10px;border-bottom:1px solid #41516a}@media(max-width:700px){.grid{grid-template-columns:1fr}}</style><h1>정수리를 낮추고 눈과 미소를 다듬었습니다</h1><p>기존 모델을 Blender에서 수정했습니다. 헤어 윗부분을 살짝 납작하게 만들고, 눈동자를 정면으로 맞췄습니다. 홍채와 작은 반사광으로 눈의 생기를 정리했으며, 속눈썹 색·턱 중앙·입꼬리·입 안의 치아 노출도 보정했습니다.</p><div class="grid">'''+fig('identity','기준 참고 이미지')+fig('front','이번 결과 · 낮춘 정수리와 부드러운 미소')+fig('angle','사선 · 눈과 입꼬리')+fig('side','측면 · 완만한 턱과 다문 입')+'''</div><h2>이전 모습과 비교</h2><div class="grid">'''+fig('before_front','이전 v3 · 높은 정수리와 기존 눈')+fig('front','이번 v4 · 낮춘 정수리와 정면 시선')+fig('before_eyes_clean','이전 눈 재질과 속눈썹')+fig('eyes_detail','새 홍채 · 작은 반사광 · 어두운 속눈썹')+'''</div><h2>입과 턱</h2><div class="grid">'''+fig('mouth_front','입꼬리를 조금 내린 기본 미소 · 치아가 드러나지 않도록 보정')+'''<figure><div><button id="closed">다문 입 · 사선</button><button id="opened">원래 열린 입</button></div><a id="mouthLink" href="mouth_closed.png" target="_blank"><img id="mouth" src="mouth_closed.png"></a><figcaption>원래 열린 입과 입 내부는 보존했습니다. Blender에서 FACE_CONTROLS → mouth_open을 0~1로 전환할 수 있습니다.</figcaption></figure></div><h2>검증</h2><table>'''+''.join(f'<tr><td>{html.escape(k)}</td><td>{html.escape(str(v))}</td></tr>' for k,v in [('눈','좌우 독립 눈알 · 중앙을 향하던 홍채를 정면으로 정렬'),('정수리','상단 높이 약 0.0344 장면 단위 감소 · 앞머리와 단발 끝 유지'),('치아 노출','정면·낮은 정면·양쪽 사선·양쪽 측면의 치아 면 중심 1,773개씩 검사 · 노출 0'),('입 모양','다문 미소 기본 · 원래 열린 입 좌표 복원 확인'),('저장과 내보내기','저장 파일 재열기 · 텍스처·버텍스 색·눈알 구조·입 모프를 포함한 GLB 재가져오기'),('추가 Tripo 사용량','0크레딧'),('기존 작업 한도 잔여',f'{check["remaining_credits"]:g}크레딧')])+'''</table><div class="grid" style="margin-top:20px">'''+fig('glb_roundtrip_front','GLB 재가져오기 렌더 · 눈 재질과 기본 표정 확인')+fig('back','후면 · 기존 단발 형태 유지')+'''</div><p><a href="model.blend">Blender 파일</a> · <a href="model.glb">텍스처 포함 GLB</a> · <a href="verification.json">검증 기록</a> · <a href="workflow-status.json">작업 상태</a></p><div class="note">현재는 모델 형태와 기본 표정 검토용 파일입니다. 전체 눈 깜빡임·시선·페이스 리깅과 게임용 메쉬 최적화는 아직 남아 있습니다.</div><script>for(const [id,file] of [['closed','mouth_closed.png'],['opened','mouth_open.png']])document.getElementById(id).onclick=()=>{document.getElementById('mouth').src=file;document.getElementById('mouthLink').href=file;};</script></html>'''
(V/'index.html').write_text(page,encoding='utf-8')
with httpx.Client(timeout=30) as c:
 response=c.get(state['review_url']);response.raise_for_status();paths=set(re.findall(r'(?:src|href)="([^"]+)"',response.text));checks={p:c.head(state['review_url']+p).status_code for p in paths if not p.startswith(('http','#'))};assert all(v==200 for v in checks.values());print(json.dumps({'review_url':state['review_url'],'linked_assets_verified':len(checks),'new_Tripo_credits':0}))
