import json,shutil,re,html,httpx
from pathlib import Path
R=Path(__file__).resolve().parents[1];A=R/'art/characters/explorer_b_face_animated_v6';V=R/'artifacts/production-lab-20261003/review/character-face-animated-v6';V.mkdir(parents=True,exist_ok=True)
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def save(p,d):p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
check=read(A/'verification.json');occ=read(A/'iris-occlusion.json');assert check['status']=='passed' and all(x['protruding_faces']==0 for x in occ);check['iris_occlusion_checks']=occ;save(A/'verification.json',check)
state={'date':'2026-10-05','state':'Blender_repaired_Rigify_animation_v6','blend':(A/'explorer_b_repaired_rigify_v6.blend').relative_to(R).as_posix(),'glb':(A/'explorer_b_repaired_rigify_v6.glb').relative_to(R).as_posix(),'new_total_credits':0,'head_regenerated':False,'hair_regenerated':False,'hair_cards':False,'mouth_pose':'closed gentle smile','eyes_separate':True,'rigged':True,'addon':'Rigify','animation_seconds':12,'fps':30,'full_production_facial_rig':False,'audio_lipsync':False,'review_url':'http://127.0.0.1:8842/character-face-animated-v6/'};save(A/'workflow-status.json',state)
p=R/'docs/CHARACTER_GENERATION_POLICY.json';d=read(p);d.update(current_stage=state['state'],current_hybrid_output='art/characters/explorer_b_face_animated_v6');d['latest_local_refinement_v6']=state;save(p,d)
p=R/'art/characters/explorer_b_pipeline_v3/pipeline.json';d=read(p);d.setdefault('historical_clean_edges_v5',d.get('current_hybrid_bust',{}));d.update(status=state['state'],current_hybrid_bust=state,current_integrated_face=state);d['current_head_p2'].update(blend=state['blend'],state=state['state'],mouth_rest_prepared=True,eyes_separate=True,rigged=True);save(p,d)
for name in ['front','angle','side','eyes_detail','eye_angle_L','eye_angle_R','mouth_corners_L','mouth_corners_R','blink_half','blink_closed','mouth_open']:shutil.copy2(A/(name+'.png'),V/(name+'.png'))
for name in ['verification.json','workflow-status.json','animation.mp4']:shutil.copy2(A/name,V/name)
shutil.copy2(A/'explorer_b_repaired_rigify_v6.blend',V/'model.blend');shutil.copy2(A/'explorer_b_repaired_rigify_v6.glb',V/'model.glb')
def fig(n,t):return f'<figure><a href="{n}.png"><img src="{n}.png" loading="lazy"></a><figcaption>{html.escape(t)}</figcaption></figure>'
page='''<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>얼굴 경계 보정 · Rigify 애니메이션 v6</title><style>body{font:17px/1.7 system-ui;max-width:1150px;margin:32px auto;padding:0 24px;background:#17212c;color:#edf3fa}a{color:#acd6ff}.grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}figure{margin:0}img,video{width:100%;border-radius:12px}video{max-height:720px;background:#333}figcaption{padding:8px}@media(max-width:700px){.grid{grid-template-columns:1fr}}</style><h1>얼굴 경계 보정과 Rigify 애니메이션</h1><p>입꼬리의 작은 틈을 맞물리게 수정하고, 문제가 있는 눈 주변 면을 연결된 눈꺼풀 메쉬로 교체했습니다. 속눈썹은 피부와 분리된 얇은 메쉬이며 앞·뒤·옆면 모두 같은 짙은 갈색 재질입니다.</p><video controls loop muted playsinline src="animation.mp4" poster="front.png"></video><p>12초 · 30fps. 천천히 시선을 옮기고 고개를 움직이며, 세 차례 깜빡이고 작은 입 움직임을 이어갑니다. 기본 표정은 입을 다문 미소입니다.</p><p>설치한 Rigify 애드온으로 실제 조작 리그를 생성했습니다. 눈꺼풀·입 변형은 이 Tripo 얼굴에 맞춰 직접 보정한 형태를 연결했습니다. MPFB 기본 얼굴 변형을 자동 이식한 모델이나 음성 립싱크는 아닙니다.</p><div class="grid">'''+fig('front','기본 상태')+fig('angle','사선 확인')+fig('eyes_detail','눈 주변 · 머리카락 숨김')+fig('blink_half','깜빡임 중간 상태')+fig('blink_closed','완전히 감은 상태')+fig('mouth_open','작은 입 움직임')+fig('mouth_corners_L','한쪽 입꼬리 확대')+fig('mouth_corners_R','반대쪽 입꼬리 확대')+fig('eye_angle_L','눈꺼풀과 속눈썹 측면')+fig('eye_angle_R','반대쪽 측면')+'''</div><p>기본 입꼬리를 양쪽 각각 5,600개 광선으로 확인했고, 깜빡임의 중간·닫힘 상태 9개 프레임에서 눈동자 돌출도 검사했습니다. 애니메이션 GLB에는 리그·모프·텍스처가 포함됩니다. 추가 Tripo 크레딧은 0입니다.</p><p><a href="model.blend">Blender 파일</a> · <a href="model.glb">애니메이션 GLB</a> · <a href="animation.mp4">MP4</a> · <a href="verification.json">검증 기록</a></p><p>Blender에서 Space로 재생합니다. jaw의 mouth_open, blink.L/R의 blink, smile의 smile 속성으로 표정을 조절할 수 있습니다. 전체 표정 세트와 게임용 최적화는 후속 단계입니다.</p></html>''';(V/'index.html').write_text(page,encoding='utf-8')
with httpx.Client(timeout=30) as c:
 res=c.get(state['review_url']);res.raise_for_status();links=set(re.findall(r'(?:src|href|poster)="([^"]+)"',res.text));statuses={x:c.head(state['review_url']+x).status_code for x in links};assert all(v==200 for v in statuses.values());print(state['review_url'],statuses)
