import json,shutil,re,httpx,hashlib
from pathlib import Path
R=Path(__file__).resolve().parents[1];A=R/'art/characters/explorer_b_user_head_v8';V=R/'artifacts/production-lab-20261003/review/character-user-head-mpfb-v8';V.mkdir(parents=True,exist_ok=True)
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def save(p,d):p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
check=read(A/'verification.json');assert check['status']=='passed';clips=read(A/'expression-clips.json');sourcehash=hashlib.sha256((A/'source_user_head.glb').read_bytes()).hexdigest()
state={'date':'2026-10-05','state':'User_GLb_head_MPFb_Rigify_expressions_v8','source':'user supplied GLB','source_glb':(A/'source_user_head.glb').relative_to(R).as_posix(),'source_sha256':sourcehash,'blend':(A/'user_head_mpfb_rigify_v8.blend').relative_to(R).as_posix(),'glb':(A/'user_head_mpfb_rigify_v8.glb').relative_to(R).as_posix(),'new_total_credits':0,'hair_regenerated':False,'hair_cards':False,'hair_source':'approved sculptural bob from v7, fitted to new head','mouth_pose':'original supplied parted-lip smile','rigged':True,'eyes_separate':True,'addons':['MPFB','Rigify'],'MPFB_donor_units_retargeted':17,'locally_fitted_blink_units':2,'animation_seconds':18,'expression_clips':clips,'fps':30,'review_url':'http://127.0.0.1:8842/character-user-head-mpfb-v8/'};save(A/'workflow-status.json',state)
p=R/'docs/CHARACTER_GENERATION_POLICY.json';d=read(p);d.update(current_stage=state['state'],current_hybrid_output='art/characters/explorer_b_user_head_v8');d['latest_user_head_v8']=state;save(p,d)
p=R/'art/characters/explorer_b_pipeline_v3/pipeline.json';d=read(p);d.setdefault('historical_expression_face_v7',d.get('current_hybrid_bust',{}));d.update(status=state['state'],current_hybrid_bust=state,current_integrated_face=state,current_head_source={'type':'user supplied GLB','source':state['source_glb'],'blend':state['blend'],'rigged':True,'mouth_rest':state['mouth_pose']});save(p,d)
for n in ['neutral','happy','concern','determined','surprise','blink_half','blink_closed','angle','side','eyes_detail','import_y']:shutil.copy2(A/(n+'.png'),V/(n+'.png'))
for n in ['animation.mp4','verification.json','rig-report.json','expression-clips.json','workflow-status.json','mpfb-retarget.json']:shutil.copy2(A/n,V/n)
shutil.copy2(A/'user_head_mpfb_rigify_v8.blend',V/'model.blend');shutil.copy2(A/'user_head_mpfb_rigify_v8.glb',V/'model.glb')
def fig(n,t):return '<figure><a href="'+n+'.png"><img src="'+n+'.png" loading="lazy"></a><figcaption>'+t+'</figcaption></figure>'
figs=''.join(fig(n,t) for n,t in [('import_y','첨부 GLB 원본 · 헤어 없이'),('neutral','새 얼굴에 기존 단발 헤어를 맞춘 기본 상태'),('happy','기쁨 · MPFB 미소와 볼 단위'),('concern','걱정 · 눈썹 안쪽과 입꼬리'),('determined','결의 · 눈썹과 입술 압력'),('surprise','놀람 · 눈썹과 턱 열기'),('blink_half','깜빡임 중간'),('blink_closed','완전히 감은 눈'),('angle','사선'),('side','측면'),('eyes_detail','눈 주변 확대')])
(V/'index.html').write_text('''<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>새 GLB 얼굴 · MPFB + Rigify v8</title><style>body{font:17px/1.7 system-ui;background:#17212c;color:#eef4fb;max-width:1150px;margin:32px auto;padding:0 24px}a{color:#acd6ff}.grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}figure{margin:0}img,video{width:100%;border-radius:12px}video{max-height:720px;background:#333}figcaption{padding:8px}.note{padding:18px;background:#29394b;border-radius:12px}@media(max-width:700px){.grid{grid-template-columns:1fr}}</style><h1>새 GLB 얼굴에 헤어를 얹고 MPFB·Rigify 표정을 연결했습니다</h1><p>첨부하신 <b>3d cartoon girl head.glb</b>의 얼굴·귀·목·쇄골과 치아·혀를 사용했습니다. 기존 단발 헤어의 크기와 위치를 맞췄으며, 눈은 독립된 눈알·홍채·반사광 부품으로 정리했습니다. 눈꺼풀과 속눈썹은 새 눈에 맞춰 연결했습니다.</p><video controls loop muted playsinline src="animation.mp4" poster="neutral.png"></video><p>18초 · 30fps. 기본 미소 → 기쁨 → 걱정 → 결의 → 놀람 → 기본 미소. 시선 이동과 깜빡임이 함께 이어집니다.</p><div class="note">이번 기본 입 모양은 첨부 GLB의 <b>입을 벌린 미소</b>입니다. 닫힌 형태로 압축했을 때 생기던 접힘을 피하고 새 얼굴의 원래 인상을 유지했습니다. 치아와 혀가 있는 입 내부도 그대로 활용했습니다.</div><h2>MPFB와 Rigify의 역할</h2><p>MPFB Faceunits 01의 눈썹·볼·입·턱 표정 단위 17개를 새 얼굴의 비율에 맞춘 좌표 대응으로 옮겼습니다. MPFB FaceService에서 표정 값을 적용·읽어 실제 작동을 검사했습니다. 큰 눈에 맞춘 깜빡임 2개는 별도로 피팅해 MPFB 호환 이름으로 연결했습니다.</p><p>Rigify 애드온으로 실제 조작 리그를 생성했습니다. <b>head</b> 조작 본의 mouthSmileLeft/Right, browInnerUp, browDownLeft/Right 등 속성으로 표정을 조절합니다. <b>jaw</b>의 jawOpen은 입 벌리기, <b>blink.L/R</b>의 blink는 눈 감기입니다.</p><div class="grid">'''+figs+'''</div><h2>저장한 애니메이션</h2><p>Blender 파일에는 전체 18초 시퀀스와 <b>기본·기쁨·걱정·결의·놀람</b> 3초 루프 5개를 저장했습니다. Space로 전체 시퀀스를 재생하거나, Action Editor에서 Face_*_Loop를 선택하고 재생 범위를 1–90으로 맞춰 개별 표정을 볼 수 있습니다. GLB에는 전체 시퀀스의 리그·모프·텍스처가 포함됩니다.</p><p>표본 22개 프레임의 MPFB 값과 메쉬 수치를 확인했고, 깜빡임 중간·닫힘 15개 프레임에서 눈동자 돌출 0을 확인했습니다. 개별 클립의 시작·끝 표정도 일치합니다. 이번 결과는 첫 표정 세트이며, 52개 전체 단위와 발음·음성 립싱크는 포함되지 않습니다.</p><p><a href="model.blend">Blender 파일</a> · <a href="model.glb">애니메이션 GLB</a> · <a href="animation.mp4">MP4 영상</a> · <a href="verification.json">검증 기록</a> · <a href="workflow-status.json">작업 상태</a></p><p>원본 GLB와 이전 v7 파일을 보존했습니다. 추가 Tripo 크레딧: <b>0</b>.</p></html>''',encoding='utf-8')
with httpx.Client(timeout=30) as c:
 response=c.get(state['review_url']);response.raise_for_status();links=set(re.findall(r'(?:src|href|poster)="([^"]+)"',response.text));codes={x:c.head(state['review_url']+x).status_code for x in links};assert all(v==200 for v in codes.values());print(state['review_url'],codes)
