from pathlib import Path
import json,shutil
R=Path(__file__).resolve().parents[1];O=R/'art/characters/explorer_b_hybrid_bust_v2';W=R/'artifacts/production-lab-20261003/review/character-hybrid-refined';W.mkdir(exist_ok=True)
files=['front.png','angle.png','side.png','face_detail.png','mouth_open.png','oral_cutaway.png','explorer_b_hybrid_bust_v2.blend','refinement-report.json','verification.json']
for f in files:shutil.copy2(O/f,W/f)
shutil.copy2(R/'art/characters/explorer_b_hybrid_bust_v1/front.png',W/'before.png')
cards=''.join(f'<article><h2>{label}</h2><a href="{file}" target="_blank"><img src="{file}" alt="{label}"></a></article>' for file,label in [('front.png','수정 후 정면'),('angle.png','사선'),('side.png','측면'),('face_detail.png','헤어를 숨긴 얼굴 상세'),('mouth_open.png','입 열기 검사'),('oral_cutaway.png','입 내부 부품 — 피부와 구강 벽을 숨긴 화면')])
(W/'index.html').write_text('''<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Explorer B · 수정본 v2</title><style>body{margin:0;background:#edf2f1;color:#233b32;font:17px/1.8 "Malgun Gothic",sans-serif}main{max-width:1080px;margin:auto;padding:32px}article{padding:24px;background:white;border-radius:16px;margin:24px 0}img{display:block;width:100%;max-height:850px;object-fit:contain}a{color:#12694e}nav{display:flex;gap:24px;flex-wrap:wrap}.note{background:#fff5da;padding:20px;border-radius:12px}</style><main><h1>Explorer B · 헤어·속눈썹·입 내부 수정본</h1><nav><a href="explorer_b_hybrid_bust_v2.blend">Blender 수정본</a><a href="before.png">이전 정면</a><a href="verification.json">검증 기록</a></nav><p>헤어를 눈 바깥으로 정리하고, 속눈썹 UV와 뿌리 위치를 수정했습니다. 코·입술·귀 주변 면 방향과 일부 작은 경계를 보정했습니다. 위·아래 치아 20개, 잇몸, 혀, 구강 안쪽 면을 추가했습니다. 이전 파일은 보존했으며 추가 API 비용은 0입니다.</p><p>Blender에서 <strong>MOUTH_INSPECTION_control</strong> 선택 → 사용자 정의 속성의 <strong>open</strong> 값을 0~1로 바꾸면 입 내부를 확인할 수 있습니다. 저장된 기본값은 0(다문 입)입니다.</p><p class="note">입 열기는 내부 배치 검사용입니다. 전체 페이스 리깅·깜빡임은 아직 연결하지 않았습니다. 원본 P2 토폴로지의 작은 경계와 입꼬리는 최종 리토폴로지 단계에서 추가 점검해야 합니다. 얼굴 색상은 여전히 검토용 정면 투영 재질입니다.</p>'''+cards+'</main></html>',encoding='utf-8')
old=R/'artifacts/production-lab-20261003/review/character-hybrid-hair-hd/index.html';txt=old.read_text(encoding='utf-8')
if 'character-hybrid-refined' not in txt:old.write_text(txt.replace('<main>','<main><p><a href="../character-hybrid-refined/">최신 수정본 v2 보기 →</a></p>',1),encoding='utf-8')
p=R/'art/characters/explorer_b_pipeline_v3/pipeline.json';d=json.loads(p.read_text(encoding='utf-8-sig'));d['current_hybrid_bust']={'blend':'art/characters/explorer_b_hybrid_bust_v2/explorer_b_hybrid_bust_v2.blend','report':'art/characters/explorer_b_hybrid_bust_v2/refinement-report.json','state':'refinement_review_pending','oral_interior':True,'mouth_opening':'inspection_morph_only','full_face_rig':False,'additional_api_credits':0};p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print('Published v2 review and updated current Blender artifact.')
p=R/'docs/CHARACTER_GENERATION_POLICY.json';d=json.loads(p.read_text(encoding='utf-8-sig'));d['current_hybrid_output']='art/characters/explorer_b_hybrid_bust_v2';d['current_stage']='hybrid_bust_refined_geometry_and_oral_interior_review';p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
