import json,shutil,re,httpx
from pathlib import Path
R=Path(__file__).resolve().parents[1];A=R/'art/characters/explorer_b_expressions_v7';V=R/'artifacts/production-lab-20261003/review/character-expressions-v7';V.mkdir(parents=True,exist_ok=True)
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def save(p,d):p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
check=read(A/'verification.json');assert check['status']=='passed' and check['hair_penetration_vertices_remaining']==0;clips=read(A/'expression-clips.json')
state={'date':'2026-10-05','state':'Blender_hair_clearance_expression_clips_v7','blend':(A/'explorer_b_expressions_v7.blend').relative_to(R).as_posix(),'glb':(A/'explorer_b_expressions_v7.glb').relative_to(R).as_posix(),'new_total_credits':0,'head_regenerated':False,'hair_regenerated':False,'hair_cards':False,'mouth_pose':'closed gentle smile','rigged':True,'eyes_separate':True,'addon':'Rigify','animation_seconds':24,'expression_clips':clips,'fps':30,'review_url':'http://127.0.0.1:8842/character-expressions-v7/'};save(A/'workflow-status.json',state)
p=R/'docs/CHARACTER_GENERATION_POLICY.json';d=read(p);d.update(current_stage=state['state'],current_hybrid_output='art/characters/explorer_b_expressions_v7');d['latest_expression_animation_v7']=state;save(p,d)
p=R/'art/characters/explorer_b_pipeline_v3/pipeline.json';d=read(p);d.setdefault('historical_animated_face_v6',d.get('current_hybrid_bust',{}));d.update(status=state['state'],current_hybrid_bust=state,current_integrated_face=state);d['current_head_p2'].update(blend=state['blend'],state=state['state'],rigged=True);save(p,d)
for n in ['neutral','happy','curious','concern','determined','surprise','blink']:shutil.copy2(A/(n+'.png'),V/(n+'.png'))
for n in ['animation.mp4','verification.json','report.json','expression-clips.json','workflow-status.json']:shutil.copy2(A/n,V/n)
shutil.copy2(A/'explorer_b_expressions_v7.blend',V/'model.blend');shutil.copy2(A/'explorer_b_expressions_v7.glb',V/'model.glb')
figs=''.join('<figure><a href="'+n+'.png"><img src="'+n+'.png" loading="lazy"></a><figcaption>'+t+'</figcaption></figure>' for n,t in [('neutral','기본 미소'),('happy','기쁨'),('curious','호기심 · 고개와 시선'),('concern','걱정'),('determined','결의'),('surprise','가벼운 놀람'),('blink','깜빡임')])
(V/'index.html').write_text('''<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>표정 애니메이션 v7</title><style>body{font:17px/1.7 system-ui;background:#17212c;color:#eef4fb;max-width:1150px;margin:32px auto;padding:0 24px}a{color:#a9d5ff}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}figure{margin:0}img,video{width:100%;border-radius:12px}video{max-height:700px}figcaption{padding:8px}@media(max-width:700px){.grid{grid-template-columns:1fr 1fr}}</style><h1>머리카락 관통 정리 · 표정 애니메이션</h1><p>승인한 v6 얼굴과 헤어를 유지하고, 피부에 들어간 머리카락을 주변 면과 함께 다듬었습니다. 헤어 토폴로지를 바꾸거나 Tripo에서 다시 생성하지 않았습니다. 검사 범위 안의 얼굴 피부 관통 정점은 0입니다.</p><video src="animation.mp4" poster="neutral.png" controls loop muted playsinline></video><p>24초 · 30fps. 기본 미소 → 기쁨 → 호기심 → 걱정 → 결의 → 놀람 → 기본 미소. 전환은 Bezier 곡선으로 이어지며, 각 표정 사이에는 깜빡임이 있습니다.</p><div class="grid">'''+figs+'''</div><p>기존 Rigify 리그에 얼굴과 눈썹의 표정 변형을 연결했습니다. Blender 파일에는 표정별 3초 루프 6개와 전체 24초 시퀀스, 이전 v6 애니메이션이 함께 저장되어 있습니다. GLB는 전체 24초 시퀀스와 리그·모프·텍스처를 포함합니다.</p><p>Blender에서 Space로 재생하세요. 표정을 수동 조절하려면 head 조작 본의 happy·concern·determined·surprise 속성을 사용합니다. 호기심은 고개 기울기와 시선으로 구성했습니다. Action Editor에서 Face_*_Loop 클립을 선택하고 재생 범위를 1–90으로 맞추면 개별 표정 루프를 볼 수 있습니다.</p><p><a href="model.blend">Blender 파일</a> · <a href="model.glb">애니메이션 GLB</a> · <a href="animation.mp4">MP4</a> · <a href="expression-clips.json">클립 목록</a> · <a href="verification.json">검증 기록</a></p><p>이번 결과는 첫 표정 세트입니다. 음성 립싱크와 전체 표정 라이브러리는 아직 포함되지 않습니다. 추가 Tripo 크레딧: 0.</p></html>''',encoding='utf-8')
with httpx.Client(timeout=30) as c:
 r=c.get(state['review_url']);r.raise_for_status();links=set(re.findall(r'(?:src|href|poster)="([^"]+)"',r.text));codes={x:c.head(state['review_url']+x).status_code for x in links};assert all(v==200 for v in codes.values());print(state['review_url'],codes)
