import json,shutil,httpx,re
from pathlib import Path
R=Path(__file__).resolve().parents[1];A=R/'art/characters/explorer_b_original_identity_v9';V=R/'artifacts/production-lab-20261003/review/character-original-identity-v9';V.mkdir(parents=True,exist_ok=True)
check=json.loads((A/'verification.json').read_text());assert check['status']=='passed' and check['animated_GLb_verified']
for name in ['neutral','happy','concern','determined','surprise','original_without_hair']:shutil.copy2(A/(name+'.png'),V/(name+'.png'))
shutil.copy2(A/'original_face_mpfb_rigify_v9.blend',V/'model.blend');shutil.copy2(A/'original_face_mpfb_rigify_v9.glb',V/'model.glb');shutil.copy2(A/'verification.json',V/'verification.json')
figs=''.join('<figure><a href="'+n+'.png"><img src="'+n+'.png"></a><figcaption>'+t+'</figcaption></figure>' for n,t in [('original_without_hair','첨부한 원본 얼굴 · 헤어 없이'),('neutral','원본 얼굴 유지 · 기존 단발 헤어 추가'),('happy','기쁨'),('concern','걱정'),('determined','결의'),('surprise','놀람')])
(V/'index.html').write_text('''<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>원본 얼굴 복원 v9</title><style>body{font:17px/1.7 system-ui;max-width:1080px;margin:32px auto;padding:0 24px;background:#18222e;color:#edf4fa}a{color:#afd9ff}.grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}figure{margin:0}img{width:100%;border-radius:12px}figcaption{padding:8px}.note{padding:18px;background:#293b50;border-radius:12px}@media(max-width:700px){.grid{grid-template-columns:1fr}}</style><h1>첨부한 원본 얼굴을 그대로 복원했습니다</h1><p>이전 작업에서 눈을 교체하고 눈꺼풀을 다시 구성하며 피부를 보정해 인상이 달라졌습니다. 이번 버전은 첨부 GLB의 얼굴·눈·눈꺼풀·눈썹·속눈썹·입을 원래 형태로 유지합니다. 헤어만 맞췄습니다.</p><div class="note">기본 표정에서 얼굴 구성품의 정점 위치를 비교했습니다. 얼굴 본체의 오차는 0이며, 눈의 최대 오차도 0.000001 미만입니다. 원본 UV와 재질을 유지했습니다. 얼굴을 깎거나 리토폴로지하지 않았습니다.</div><div class="grid">'''+figs+'''</div><h2>표정 조작</h2><p>MPFB 표정 단위 19개를 별도 셰이프 키로 연결하고 Rigify 리그를 생성했습니다. 기본 → 기쁨 → 걱정 → 결의 → 놀람 → 기본으로 이어지는 15초 시퀀스를 Blender 파일에 저장했습니다. Space로 재생하거나 head 본의 표정 속성을 조절할 수 있습니다.</p><p>이 표정들은 첫 세트입니다. 완전한 눈 감기 피팅과 발음·음성 립싱크는 아직 완성되지 않았습니다. 기본 입은 첨부 모델의 입이 살짝 벌어진 미소를 유지합니다.</p><p><a href="model.blend">Blender 파일</a> · <a href="model.glb">애니메이션 GLB</a> · <a href="verification.json">검증 기록</a></p><p>첨부 원본과 이전 버전을 보존했습니다. 추가 Tripo 크레딧: 0.</p></html>''',encoding='utf-8')
state={'date':'2026-10-05','state':'Original_user_GLb_identity_restored_v9','blend':(A/'original_face_mpfb_rigify_v9.blend').relative_to(R).as_posix(),'glb':(A/'original_face_mpfb_rigify_v9.glb').relative_to(R).as_posix(),'original_face_preserved':True,'original_eyes_preserved':True,'addons':['MPFB','Rigify'],'MPFB_units':19,'full_blink_complete':False,'animation_seconds':15,'review_url':'http://127.0.0.1:8842/character-original-identity-v9/','credits':0}
(A/'workflow-status.json').write_text(json.dumps(state,ensure_ascii=False,indent=2),encoding='utf-8')
for p in [R/'docs/CHARACTER_GENERATION_POLICY.json',R/'art/characters/explorer_b_pipeline_v3/pipeline.json']:
 d=json.loads(p.read_text(encoding='utf-8-sig'));d['latest_original_identity_v9']=state
 if p.name=='CHARACTER_GENERATION_POLICY.json':d.update(current_stage=state['state'],current_hybrid_output=A.relative_to(R).as_posix())
 else:d.setdefault('historical_expression_face_v7',d.get('current_hybrid_bust',{}));d.update(status=state['state'],current_hybrid_bust=state,current_integrated_face=state,current_head_source={'type':'original user supplied GLB','source':'art/characters/explorer_b_user_head_v8/source_user_head.glb','blend':state['blend'],'neutral_geometry_preserved':True})
 p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
with httpx.Client(timeout=30) as c:
 r=c.get(state['review_url']);r.raise_for_status();links=set(re.findall(r'(?:src|href)="([^"]+)"',r.text));codes={x:c.head(state['review_url']+x).status_code for x in links};assert all(v==200 for v in codes.values());print(state['review_url'],codes)
