import json,shutil,html,re,httpx
from pathlib import Path
R=Path(__file__).resolve().parents[1];A=R/'art/characters/explorer_b_clean_edges_v5/assembly';OLD=R/'art/characters/explorer_b_face_balance_v4/assembly';V=R/'artifacts/production-lab-20261003/review/character-clean-edges-v5';V.mkdir(parents=True,exist_ok=True)
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def save(p,d):p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
check=read(A/'verification.json');assert check['status']=='passed';assert (A/'godot_compatibility.png').exists();assert 'ACTUAL_GODOT_CAPTURE renderer=gl_compatibility result=0' in (R/'artifacts/godot-face-v5.log').read_text(encoding='utf-8-sig');check['godot_gpu_capture']={'success':True,'renderer':'gl_compatibility','size':[900,1000],'device':'NVIDIA GeForce RTX 2070','comparison_scene_only':True,'game_material_and_lighting_polish_complete':False};save(A/'verification.json',check)
state={'date':'2026-10-05','state':'Blender_clean_lash_boundary_rounded_chin_v5','blend':(A/'explorer_b_clean_edges_v5.blend').relative_to(R).as_posix(),'glb':(A/'explorer_b_clean_edges_v5.glb').relative_to(R).as_posix(),'new_total_credits':0,'head_regenerated':False,'hair_regenerated':False,'hair_cards':False,'mouth_pose':'relaxed closed smile','mouth_control':'FACE_CONTROLS["mouth_open"]','original_open_pose_preserved':True,'eyes':'Separate forward-looking globes and iris caps retained','lashes':'Five upper-lash UV surface charts use uniform dark material; skin and tear duct charts retain original atlas; skin vertex tint removed','chin':'Broad lower-face surface fairing; smooth U contour','game_preview':'Actual Godot Compatibility/OpenGL capture with review lighting; not the gameplay scene','full_face_rig':False,'game_low_poly_final':False,'review_url':'http://127.0.0.1:8842/character-clean-edges-v5/'}
save(A/'workflow-status.json',state)
p=R/'docs/CHARACTER_GENERATION_POLICY.json';policy=read(p);policy.update(current_stage=state['state'],current_hybrid_output='art/characters/explorer_b_clean_edges_v5');policy['latest_local_refinement_v5']={'date':'2026-10-05','user_instruction':'눈 주변 검은 텍스처 번짐과 턱 아래 얕은 M자 굴곡을 수정. 게임 렌더링과 Blender 렌더의 차이 확인.','state':state,'credits':0};save(p,policy)
p=R/'art/characters/explorer_b_pipeline_v3/pipeline.json';pipeline=read(p);pipeline.setdefault('historical_face_balance_v4',pipeline.get('current_hybrid_bust',{}));pipeline.update(status=state['state'],current_hybrid_bust=state,current_integrated_face=state);pipeline['current_head_p2'].update(blend=state['blend'],state=state['state'],mouth_rest_prepared=True,eyes_separate=True,rigged=False);save(p,pipeline)
for n in ['front','angle','side','eyes_detail','eye_angle_L','eye_angle_R','mouth_front','mouth_closed','mouth_open','glb_roundtrip_front','godot_compatibility']:shutil.copy2(A/(n+'.png'),V/(n+'.png'))
for n in ['front','eyes_detail','mouth_front']:shutil.copy2(OLD/(n+'.png'),V/('before_'+n+'.png'))
shutil.copy2(R/'art/references/explorer_b_integrated_face_haircards_v1/00_user_identity_reference.png',V/'identity.png');shutil.copy2(A/'explorer_b_clean_edges_v5.blend',V/'model.blend');shutil.copy2(A/'explorer_b_clean_edges_v5.glb',V/'model.glb')
for n in ['verification.json','workflow-status.json']:shutil.copy2(A/n,V/n)
def fig(n,t):return f'<figure><a href="{n}.png"><img src="{n}.png" alt="{html.escape(t)}" loading="lazy"></a><figcaption>{html.escape(t)}</figcaption></figure>'
page='''<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>눈 주변 번짐 정리 · 완만한 턱 · 게임 렌더 비교</title><style>body{font:17px/1.7 system-ui;background:#171d26;color:#edf3fa;max-width:1200px;margin:32px auto;padding:0 24px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}figure{margin:0}img{width:100%;border-radius:12px}figcaption{padding:9px;color:#ced8e5}a{color:#a9d5ff}.note{padding:18px;background:#29394d;border-radius:12px}h2{margin-top:36px}@media(max-width:700px){.grid{grid-template-columns:1fr}}</style><h1>눈 주변 번짐을 정리하고 턱 윤곽을 둥글게 다듬었습니다</h1><p>피부까지 퍼지던 검은 버텍스 보정을 제거하고, 실제 위 속눈썹 면에만 어두운 재질을 지정했습니다. 눈 앞머리와 눈꺼풀 피부는 원래 피부 텍스처를 유지합니다. 턱은 아래쪽 면을 넓게 다듬어 U자 윤곽으로 이어지도록 했습니다.</p><div class="grid">'''+fig('identity','참고 이미지')+fig('front','이번 v5 · Blender Cycles')+fig('angle','사선 · 피부와 속눈썹 경계')+fig('side','측면 · 다문 입과 턱')+'''</div><h2>게임에서도 렌더처럼 보이나요?</h2><p>게임도 매 프레임 실시간 렌더링합니다. 비슷한 분위기를 낼 수 있지만 Blender Cycles 사진이 자동으로 같은 모습으로 표시되지는 않습니다. 현재 프로젝트는 Godot Compatibility(OpenGL)를 사용하며, 조명·환경 반사·재질·그림자·색 보정에 따라 결과가 달라집니다.</p><div class="grid">'''+fig('front','Blender Cycles · 스튜디오 조명')+fig('godot_compatibility','실제 Godot Compatibility · 비교용 조명으로 실행해 캡처')+'''</div><div class="note">Godot 이미지는 현재 프로젝트와 같은 렌더러에서 이 GLB를 불러온 검토 장면입니다. 실제 플레이 장면의 조명이나 최종 게임 품질을 확정한 화면은 아닙니다. 피부의 부드러운 빛 퍼짐 등 Cycles 효과는 별도로 맞춰야 하며, Compatibility는 피부의 Subsurface Scattering을 지원하지 않습니다. <a href="https://docs.godotengine.org/en/stable/tutorials/rendering/renderers.html">Godot 공식 렌더러 비교</a></div><h2>눈 주변 확대</h2><div class="grid">'''+fig('before_eyes_detail','이전 v4 · 피부까지 퍼지던 검은 보정색')+fig('eyes_detail','이번 v5 · 실제 속눈썹 면만 어둡게')+fig('eye_angle_L','사선 확대 · 한쪽 눈')+fig('eye_angle_R','사선 확대 · 반대쪽 눈')+'''</div><h2>턱과 입</h2><div class="grid">'''+fig('before_mouth_front','이전 v4 · 턱 윤곽')+fig('mouth_front','이번 v5 · 완만하게 이어지는 턱 아래 윤곽')+fig('mouth_closed','기본 · 다문 미소')+fig('mouth_open','원래 열린 입 형태 보존')+'''</div><p>폴리곤 추가 없이 기존 메쉬를 다듬었습니다. 치아 면 중심 1,773개를 6개 방향에서 검사했고, 다문 상태에서 노출 0을 확인했습니다. GLB 재가져오기와 기본 입 상태·열린 입 모프도 확인했습니다. 추가 Tripo 사용은 0크레딧입니다.</p><div class="grid">'''+fig('glb_roundtrip_front','텍스처 포함 GLB 재가져오기 · 기본 표정 확인')+fig('before_front','이전 v4 전체 모습')+'''</div><p><a href="model.blend">Blender 파일</a> · <a href="model.glb">텍스처 포함 GLB</a> · <a href="verification.json">검증 기록</a> · <a href="workflow-status.json">작업 상태</a></p><p>전체 페이스 리깅과 게임용 메쉬 최적화는 아직 남아 있습니다.</p></html>'''
(V/'index.html').write_text(page,encoding='utf-8')
with httpx.Client(timeout=30) as c:
 response=c.get(state['review_url']);response.raise_for_status();paths=set(re.findall(r'(?:src|href)="([^"]+)"',response.text));checks={p:c.head(state['review_url']+p).status_code for p in paths if not p.startswith(('http','#'))};assert all(v==200 for v in checks.values());print(json.dumps({'review_url':state['review_url'],'linked_assets_verified':len(checks),'new_Tripo_credits':0}))
